GatewayWeb/urls.py
from django.conf.urls import url
from GatewayWeb.views.Index import Index
from GatewayWeb.views.Mypage import Mypage
from GatewayWeb.views.Admin.CommandManage import EditCommand, UpdateCommand, DeleteCommand, CreateCommand
from GatewayWeb.views.Admin.UserManage import EditUsers, CreateUser, UpdateUser, DeleteUser
from django.contrib.auth.views import login, logout, password_change
from GatewayWeb.forms.accounts.forms import LoginForm

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^mypage/', Mypage.as_view(), name='mypage'),
    url(r'^admin/createcommand/', CreateCommand.as_view(), name='createcommand'),
    url(r'^admin/editcommands/', EditCommand.as_view(), name='editcommands'),
    url(r'^admin/updatecommand/(?P<pk>\d+)$', UpdateCommand.as_view(), name='updatecommand'),
    url(r'^admin/deletecommand/(?P<pk>\d+)$', DeleteCommand.as_view(), name='deletecommand'),
    url(r'^admin/editusers/', EditUsers.as_view(), name='editusers'),
    url(r'^admin/createuser/', CreateUser.as_view(), name='createuser'),
    url(r'^admin/updateuser/(?P<pk>\d+)$', UpdateUser.as_view(), name='updateuser'),
    url(r'^admin/deleteuser/(?P<pk>\d+)$', DeleteUser.as_view(), name='deleteuser'),
    url(r'^login/$', login,
        {'template_name': 'GatewayWeb/accounts/login.html', 'authentication_form': LoginForm, 'redirect_authenticated_user': True}, name='login'),
    url(r'^logout/$', logout,
        {'template_name': 'GatewayWeb/accounts/logout.html'}, name='logout'),
    url(r'^changepasswd/$', password_change,
        {'template_name': 'GatewayWeb/accounts/changepasswd.html', 'post_change_redirect': '/scg/mypage/'}, name='changepasswd'),
]

SimpleCommandGateway/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^scg/', include('GatewayWeb.urls', namespace='gatewayweb')),
]

GatewayWeb/models/Command.py
from django.db import models


class Command(models.Model):
    name = models.CharField(max_length=100, default='name')
    detail = models.CharField(max_length=1000, default='details')
    command = models.CharField(max_length=100, default='whoami')

    class Meta:
        ordering = ('id', )

GatewayWeb/forms/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'forms-control'
        self.fields['password'].widget.attrs['class'] = 'forms-control'

GatewayWeb/views/Index.py
from django.views.generic import TemplateView
from GatewayWeb.models.Command import *
from django.contrib.auth.mixins import LoginRequiredMixin


class Index(LoginRequiredMixin, TemplateView):

    template_name = 'GatewayWeb/index.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['commands'] = Command.objects.all()
        return context

GatewayWeb/views/Mypage.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class Mypage(LoginRequiredMixin, TemplateView):

    template_name = 'GatewayWeb/mypage.html'

    def get_context_data(self, **kwargs):
        context = super(Mypage, self).get_context_data(**kwargs)
        return context

GatewayWeb/templates/GatewayWeb/Admin/createcommand.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
ADD COMMAND
{% endblock title %}

{% block gwcontents %}
    <div class="container text-left">
        <div class="row">
            <h1>コマンドを登録</h1>
        </div>
        <div class="row">
            <div class="col-md-5">
                <form class="my-form" method="POST">
                    {% bootstrap_form form %}
                    {% csrf_token %}
                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-default" value="登録">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock gwcontents %}

GatewayWeb/templates/GatewayWeb/Admin/createuser.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
ADD USER
{% endblock title %}

{% block gwcontents %}
    <div class="container text-left">
        <div class="row">
            <h1>ユーザーを登録</h1>
        </div>
        <div class="row">
            <div class="col-md-5">
                <form class="my-form" method="POST">
                    {% bootstrap_form form %}
                    {% csrf_token %}
                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-default" value="登録">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock gwcontents %}

GatewayWeb/templates/GatewayWeb/Admin/deletecommand.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
DELETE COMMAND
{% endblock title %}

{% block gwcontents %}
    <div class="container text-left">
        <div class="row">
            <h1>コマンドを削除</h1>
        </div>
        <div class="row">
            <h2>{{ object.name }}を本当に削除しますか?</h2>
        </div>
        <div class="row">
            <div class="col-md-5">
                <form class="my-form" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-danger"  value="削除">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock gwcontents %}

GatewayWeb/templates/GatewayWeb/Admin/deleteuser.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
DELETE USER
{% endblock title %}

{% block gwcontents %}
    <div class="container text-left">
        <div class="row">
            <h1>ユーザーを削除</h1>
        </div>
        <div class="row">
            <h2>{{ object.username }}を本当に削除しますか?</h2>
        </div>
        <div class="row">
            <div class="col-md-5">
                <form class="my-form" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-danger"  value="削除">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock gwcontents %}

GatewayWeb/templates/GatewayWeb/Admin/editcommands.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
Edit Commands
{% endblock title %}

{% block gwcontents %}
<div class="container text-left">
    <div class="row">
        <h1>コマンド一覧</h1>
    </div>
    <div class="row">
        <a class="btn btn-default" href="{% url 'gatewayweb:createcommand' %}">コマンドを登録</a>
    </div>
    <div class="row">
        <div class="col-md-11 col-md-offset-0.5" style="padding-top:5px;">
            <table class="table table-striped">
                <tr>
                    <th>id</th>
                    <th>コマンド名</th>
                    <th>コマンドの説明</th>
                    <th>コマンド</th>
                    <th></th>
                </tr>
                {% for command in commands %}
                <tr>
                    <td>{{ command.id }}</td>
                    <td>{{ command.name }}</td>
                    <td>{{ command.detail }}</td>
                    <td>{{ command.command }}</td>
                    <td><a class="btn btn-default" href="{% url 'gatewayweb:updatecommand' pk=command.id %}">編集</a></td>
                </tr>
                {% endfor %}
            </table>
            </dl>
        </div>
    </div>
</div>
{% endblock gwcontents %}

GatewayWeb/templates/GatewayWeb/Admin/editusers.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
Edit Users
{% endblock title %}

{% block gwcontents %}
<div class="container text-left">
    <div class="row">
        <h1>ユーザー一覧</h1>
    </div>
    <div class="row">
        <a class="btn btn-default" href="{% url 'gatewayweb:createuser' %}">ユーザーを登録</a>
    </div>
    <div class="row">
        <div class="col-md-11 col-md-offset-0.5" style="padding-top:5px;">
            <table class="table table-striped">
                <tr>
                    <th>ユーザー名</th>
                    <th>メールアドレス</th>
                    <th>管理者区別</th>
                    <th>有効区別</th>
                    <th>登録日</th>
                    <th></th>
                </tr>
                {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email}}</td>
                    <td>{{ user.is_superuser }}</td>
                    <td>{{ user.is_active }}</td>
                    <td>{{ user.date_joined }}</td>
                    <td><a class="btn btn-default" href="{% url 'gatewayweb:updateuser' user.id %}">編集</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock gwcontents %}

GatewayWeb/templates/GatewayWeb/Admin/updatecommand.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
UPDATE COMMAND
{% endblock title %}

{% block gwcontents %}
    <div class="container text-left">
        <div class="row">
            <h1>コマンドを編集</h1>
        </div>
        <div class="row">
            <div class="col-md-5">
                <form class="my-form" method="POST">
                    {% bootstrap_form form %}
                    {% csrf_token %}
                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-default" value="登録">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock gwcontents %}

GatewayWeb/templates/GatewayWeb/Admin/updateuser.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
UPDATE USER
{% endblock title %}

{% block gwcontents %}
    <div class="container text-left">
        <div class="row">
            <h1>ユーザーを編集</h1>
        </div>
        <div class="row">
            <div class="col-md-5">
                <form class="my-form" method="POST">
                    {% bootstrap_form form %}
                    {% csrf_token %}
                    <div class="form-group">
                        <div>
                            <input type="submit" class="btn btn-default" value="登録">
                            <a class="btn btn-danger" href="{% url 'gatewayweb:deleteuser' pk=object.id %}">削除</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock gwcontents %}

GatewayWeb/templates/GatewayWeb/accounts/changepasswd.html
{% extends 'base.html' %}

{% block title %}
Chanage Password
{% endblock title %}

{% block contents %}

<div class="container text-center">
    <div class="row">
        <h1>Chanage Password</h1>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <p class="bg-danger">
            </p><br>
            <form class="my-form" method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                <div class="form-group">
                    <div>
                        <input type="submit" class="btn btn-default" value="保存">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contents %}

GatewayWeb/templates/GatewayWeb/accounts/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock title %}

{% block contents %}

<div class="container text-center">
    <div class="row">
        <h1>LOGIN</h1>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <p class="bg-danger">
            </p><br>
            <form class="my-form" method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                <div class="form-group">
                    <div>
                        <input type="submit" class="btn btn-default" value="ログイン">
                    </div>
                </div>
                <input type="hidden" name="next" value="{% if next %}{{next}}{% endif %}"/>
            </form>
        </div>
    </div>
</div>
{% endblock contents %}

GatewayWeb/templates/GatewayWeb/accounts/logout.html
{% extends 'base.html' %}

{% block meta %}
<meta http-equiv="refresh" content="3;URL={% url 'gatewayweb:index' %}">
{% endblock meta%}

{% block title %}
Logout
{% endblock title %}

{% block contents %}
<div class="container text-center">
    <div class="row">
        <p>Logged out.</p>
        <p class="text-info">3秒後にトップページにリダイレクトします.</p>
    </div>
</div>
{% endblock contents %}

GatewayWeb/templates/GatewayWeb/gwbase.html
{% extends 'base.html' %}
{% block contents %}
<div class="container-fluid">
    <nav class="navbar navbar-inverse">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
                <span class="sr-only">メニュー</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <a href="{% url 'gatewayweb:index' %}" class="navbar-brand">GatewayWeb</a>
                <li><a href="{% url 'gatewayweb:mypage' %}">Mypage</a></li>
            </ul>
            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    {% if request.user.is_superuser %}
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button">AdminTools<b class="caret"></b></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'gatewayweb:editcommands' %}">Edit Commands</a></li>
                                <li><a href="{% url 'gatewayweb:editusers' %}">Edit Users</a></li>
                            </ul>
                        </li>
                    {% endif %}
                    <li><a href="{% url 'gatewayweb:logout' %}">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    {% block gwcontents %}
    {% endblock %}
</div>
{% endblock contents %}

GatewayWeb/templates/GatewayWeb/index.html
{% extends 'GatewayWeb/gwbase.html' %}
{% load staticfiles %}
{% block title %}
INDEX
{% endblock title %}

{% block gwcontents %}
<div class="container text-left">
    <div class="row row-eq-height">
        <div class="col-xs-2 col-md-2">
            <dl>
                {% for command in commands %}
                <dt>
                    <button type="button" id="{{command.id}}"
                            class="btn btn-default commandbtn" value="{{ command.name }}" >
                        {{ command.name }}
                    </button>
                </dt>
                <dd>{{ command.detail }}</dd>
                {% endfor %}
            </dl>
        </div>
        <div class="panel panel-default, col-xs-10 col-md-10">
            <div class="panel panel-default">
                <div class="panel-heading">コマンド出力結果</div>

                <div id="cmdpanel" class="panel-body " >
                    <pre class="pre-scrollable" id="cmdpre" style="background-color: black;">
                    </pre>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock gwcontents %}

{% block afterbody %}
    <script type="text/javascript" src='{% static "js/reconnecting-websocket.min.js" %}'></script>
    <script type="text/javascript" src="{% static 'js/command.js' %}"></script>
    <style type="text/css">
        .pre-scrollable {
            height: 500px;
            max-height: 500px;
            overflow-y: scroll;
        }
    </style>
{% endblock afterbody %}

GatewayWeb/templates/GatewayWeb/mypage.html
{% extends 'GatewayWeb/gwbase.html' %}

{% block title %}
INDEX
{% endblock title %}

{% block gwcontents %}
<div class="container text-left">
    <div class="row">
        <h1>{{ request.user.username }}さんのマイページ</h1>
    </div>
    <div class="row">
        <a class="btn btn-default" href="{% url 'gatewayweb:changepasswd' %}">パスワードを変更</a>
    </div>
</div>
{% endblock gwcontents %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% bootstrap_css %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}{% endblock %}
    <title>{% block title %}Awesome my webpage{% endblock %}</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <![endif]-->
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block bootstrap3_extra_head %}{% endblock %}{% bootstrap_css %}
    {# jqueryのあとにbootstrapjsを読み込まないとnavのdroppdownが動かない #}
    <script
                type="text/javascript"
            src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
            crossorigin="anonymous"></script>
    {% bootstrap_javascript %}
</head>

<body>
<div class="container">
    {% block contents %}{% endblock %}
</div><!-- /.container -->
{% block afterbody %}
{% endblock %}
</body>
</html>